
export enum OpPrecedence {
    Yields = '<',
    Same = '=',
    Over = '>',
    Error = '',
}

export const OPTable: Record<string, Record<string, OpPrecedence>> = {
    '+': {
        '+': OpPrecedence.Over, 
        '-': OpPrecedence.Over, 
        '*': OpPrecedence.Yields, 
        '/': OpPrecedence.Yields, 
        '(': OpPrecedence.Yields, 
        ')': OpPrecedence.Over, 
        '<': OpPrecedence.Over, 
        '<=': OpPrecedence.Over,
        '>': OpPrecedence.Over,
        '>=': OpPrecedence.Over,
        '==': OpPrecedence.Over,
        '<>': OpPrecedence.Over,
        'const': OpPrecedence.Yields,
        '$': OpPrecedence.Over,
    },
    '-': {
        '+': OpPrecedence.Over, 
        '-': OpPrecedence.Over, 
        '*': OpPrecedence.Yields, 
        '/': OpPrecedence.Yields, 
        '(': OpPrecedence.Yields, 
        ')': OpPrecedence.Over, 
        '<': OpPrecedence.Over, 
        '<=': OpPrecedence.Over,
        '>': OpPrecedence.Over,
        '>=': OpPrecedence.Over,
        '==': OpPrecedence.Over,
        '<>': OpPrecedence.Over,
        'const': OpPrecedence.Yields,
        '$': OpPrecedence.Over,
    },
    '*': {
        '+': OpPrecedence.Over, 
        '-': OpPrecedence.Over, 
        '*': OpPrecedence.Over, 
        '/': OpPrecedence.Over, 
        '(': OpPrecedence.Yields, 
        ')': OpPrecedence.Over, 
        '<': OpPrecedence.Over, 
        '<=': OpPrecedence.Over,
        '>': OpPrecedence.Over,
        '>=': OpPrecedence.Over,
        '==': OpPrecedence.Over,
        '<>': OpPrecedence.Over,
        'const': OpPrecedence.Yields,
        '$': OpPrecedence.Over,
    },
    '/': {
        '+': OpPrecedence.Over, 
        '-': OpPrecedence.Over, 
        '*': OpPrecedence.Over, 
        '/': OpPrecedence.Over, 
        '(': OpPrecedence.Yields, 
        ')': OpPrecedence.Over, 
        '<': OpPrecedence.Over, 
        '<=': OpPrecedence.Over,
        '>': OpPrecedence.Over,
        '>=': OpPrecedence.Over,
        '==': OpPrecedence.Over,
        '<>': OpPrecedence.Over,
        'const': OpPrecedence.Yields,
        '$': OpPrecedence.Over,
    },
    '(': {
        '+': OpPrecedence.Yields, 
        '-': OpPrecedence.Yields, 
        '*': OpPrecedence.Yields, 
        '/': OpPrecedence.Yields, 
        '(': OpPrecedence.Yields, 
        ')': OpPrecedence.Same, 
        '<': OpPrecedence.Yields, 
        '<=': OpPrecedence.Yields,
        '>': OpPrecedence.Yields,
        '>=': OpPrecedence.Yields,
        '==': OpPrecedence.Yields,
        '<>': OpPrecedence.Yields,
        'const': OpPrecedence.Yields,
        '$': OpPrecedence.Error,
    },
    ')': {
        '+': OpPrecedence.Over, 
        '-': OpPrecedence.Over, 
        '*': OpPrecedence.Over, 
        '/': OpPrecedence.Over, 
        '(': OpPrecedence.Error, 
        ')': OpPrecedence.Over, 
        '<': OpPrecedence.Over, 
        '<=': OpPrecedence.Over,
        '>': OpPrecedence.Over,
        '>=': OpPrecedence.Over,
        '==': OpPrecedence.Over,
        '<>': OpPrecedence.Over,
        'const': OpPrecedence.Error,
        '$': OpPrecedence.Over,
    },
    '<': {
        '+': OpPrecedence.Yields, 
        '-': OpPrecedence.Yields, 
        '*': OpPrecedence.Yields, 
        '/': OpPrecedence.Yields, 
        '(': OpPrecedence.Yields, 
        ')': OpPrecedence.Over, 
        '<': OpPrecedence.Over, 
        '<=': OpPrecedence.Over,
        '>': OpPrecedence.Over,
        '>=': OpPrecedence.Over,
        '==': OpPrecedence.Over,
        '<>': OpPrecedence.Over,
        'const': OpPrecedence.Yields,
        '$': OpPrecedence.Over,
    },
    '<=': {
        '+': OpPrecedence.Yields, 
        '-': OpPrecedence.Yields, 
        '*': OpPrecedence.Yields, 
        '/': OpPrecedence.Yields, 
        '(': OpPrecedence.Yields, 
        ')': OpPrecedence.Over, 
        '<': OpPrecedence.Over, 
        '<=': OpPrecedence.Over,
        '>': OpPrecedence.Over,
        '>=': OpPrecedence.Over,
        '==': OpPrecedence.Over,
        '<>': OpPrecedence.Over,
        'const': OpPrecedence.Yields,
        '$': OpPrecedence.Over,
    },
    '>': {
        '+': OpPrecedence.Yields, 
        '-': OpPrecedence.Yields, 
        '*': OpPrecedence.Yields, 
        '/': OpPrecedence.Yields, 
        '(': OpPrecedence.Yields, 
        ')': OpPrecedence.Over, 
        '<': OpPrecedence.Over, 
        '<=': OpPrecedence.Over,
        '>': OpPrecedence.Over,
        '>=': OpPrecedence.Over,
        '==': OpPrecedence.Over,
        '<>': OpPrecedence.Over,
        'const': OpPrecedence.Yields,
        '$': OpPrecedence.Over,
    },
    '>=': {
        '+': OpPrecedence.Yields, 
        '-': OpPrecedence.Yields, 
        '*': OpPrecedence.Yields, 
        '/': OpPrecedence.Yields, 
        '(': OpPrecedence.Yields, 
        ')': OpPrecedence.Over, 
        '<': OpPrecedence.Over, 
        '<=': OpPrecedence.Over,
        '>': OpPrecedence.Over,
        '>=': OpPrecedence.Over,
        '==': OpPrecedence.Over,
        '<>': OpPrecedence.Over,
        'const': OpPrecedence.Yields,
        '$': OpPrecedence.Over,
    },
    '==': {
        '+': OpPrecedence.Yields, 
        '-': OpPrecedence.Yields, 
        '*': OpPrecedence.Yields, 
        '/': OpPrecedence.Yields, 
        '(': OpPrecedence.Yields, 
        ')': OpPrecedence.Over, 
        '<': OpPrecedence.Yields, 
        '<=': OpPrecedence.Yields,
        '>': OpPrecedence.Yields,
        '>=': OpPrecedence.Yields,
        '==': OpPrecedence.Over,
        '<>': OpPrecedence.Over,
        'const': OpPrecedence.Yields,
        '$': OpPrecedence.Over,
    },
    '<>': {
        '+': OpPrecedence.Yields, 
        '-': OpPrecedence.Yields, 
        '*': OpPrecedence.Yields, 
        '/': OpPrecedence.Yields, 
        '(': OpPrecedence.Yields, 
        ')': OpPrecedence.Over, 
        '<': OpPrecedence.Yields, 
        '<=': OpPrecedence.Yields,
        '>': OpPrecedence.Yields,
        '>=': OpPrecedence.Yields,
        '==': OpPrecedence.Over,
        '<>': OpPrecedence.Over,
        'const': OpPrecedence.Yields,
        '$': OpPrecedence.Over,
    },
    'const': {
        '+': OpPrecedence.Over, 
        '-': OpPrecedence.Over, 
        '*': OpPrecedence.Over, 
        '/': OpPrecedence.Over, 
        '(': OpPrecedence.Error, 
        ')': OpPrecedence.Over, 
        '<': OpPrecedence.Over, 
        '<=': OpPrecedence.Over,
        '>': OpPrecedence.Over,
        '>=': OpPrecedence.Over,
        '==': OpPrecedence.Over,
        '<>': OpPrecedence.Over,
        'const': OpPrecedence.Error,
        '$': OpPrecedence.Over,
    },
    '$': {
        '+': OpPrecedence.Yields, 
        '-': OpPrecedence.Yields, 
        '*': OpPrecedence.Yields, 
        '/': OpPrecedence.Yields, 
        '(': OpPrecedence.Yields, 
        ')': OpPrecedence.Error, 
        '<': OpPrecedence.Yields, 
        '<=': OpPrecedence.Yields,
        '>': OpPrecedence.Yields,
        '>=': OpPrecedence.Yields,
        '==': OpPrecedence.Yields,
        '<>': OpPrecedence.Yields,
        'const': OpPrecedence.Yields,
        '$': OpPrecedence.Error,
    }
}